COLUMNS = [
        "CLEANSED OUT (COMBINATION ALL CHECKS)",
        "ID_NUMBER",
        "Contact Number",
        "First name",
        "Last name",
        "Full name",
        "Birthday",
        "Email",
        "Mobile",
        "City",
        "Country",
        "Postcode",
        "I am a fan of - UECLF 2024 (extended export)",
        "'Increase your chances - UELF 2024'",
        "'I want to take part in the draw - UELF 2024'",
        "Tenant ID",
        "Application for UECLF?",
        "Application for UELF?",
        "Application for UCLF?",
        "Risk Score",
        "Provider Country",
        "Provider City",
        "Provider",
        "Browser language",
        "Browser",
        "Order Date",
        "Order Number",
        "IP short",
        "Combined Address"
    ]


        # Column renames (rename step)
RENAMES = {
        "CLEANSED OUT (COMBINATION ALL CHECKS)": "cleansed",
        "ID_NUMBER": "passport_id",
        "Contact Number": "contact_number",
        "First name": "first_name",
        "Last name": "last_name",
        "Full name": "full_name",
        "Birthday": "birthday",
        "Email": "email",
        "Mobile": "mobile",
        "City": "city",
        "Country": "country",
        "Postcode": "postcode",
        "I am a fan of - UECLF 2024 (extended export)": "ueclf_24_fan_of",
        "'Increase your chances - UELF 2024'": "uelf_24_app_increase_chances",
        "'I want to take part in the draw - UELF 2024'": "uelf_24_app",
        "Tenant ID": "competition_id",
        "Application for UECLF?": "ueclf_24_app",
        "Application for UELF?": "uelf_25_app",
        "Application for UCLF?": "uclf_24_app",
        "Risk Score": "risk_ident_score",
        "Provider Country": "provider_country",
        "Provider City": "provider_city",
        "Provider": "provider",
        "Browser language": "browser_language",
        "Browser": "browser",
        "Order Date": "app_date",
        "Order Number": "app_id",
        "IP short": "ip_short",
        "Combined Address": "combined_address",
    }